# Generated by Django 5.2.1 on 2026-05-16 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_company_branch_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name_plural': 'Companies'},
        ),
    ]
