# -*- coding: utf-8 -*-
# Generated by Django 5.2.1 on 2026-05-16 08:55
from django.db import migrations, models
import django.db.models.deletion


def backfill_branch(apps, schema_editor):
    """
    Assign existing Category, Product, and Customer rows to the first
    active branch found.  On a fresh database there is nothing to do.
    Adjust this logic if you already have live data spread across branches.
    """
    Branch   = apps.get_model("pos", "Branch")
    Category = apps.get_model("pos", "Category")
    Product  = apps.get_model("pos", "Product")
    Customer = apps.get_model("pos", "Customer")

    default_branch = Branch.objects.filter(is_active=True).order_by("id").first()
    if default_branch is None:
        return

    Category.objects.filter(branch__isnull=True).update(branch=default_branch)
    Product.objects.filter(branch__isnull=True).update(branch=default_branch)
    Customer.objects.filter(branch__isnull=True).update(branch=default_branch)


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0004_alter_branch_options_alter_company_options"),
    ]

    operations = [
        # ── Category: add branch FK ──────────────────────────────────────────
        migrations.AddField(
            model_name="category",
            name="branch",
            field=models.ForeignKey(
                null=True, blank=True,          # nullable only during backfill
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="pos.branch",
            ),
        ),
        # Remove the global unique constraint on name by setting unique=False
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=120, unique=False),
        ),
        # ── Product: add branch FK ───────────────────────────────────────────
        migrations.AddField(
            model_name="product",
            name="branch",
            field=models.ForeignKey(
                null=True, blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="pos.branch",
            ),
        ),
        # Remove the global unique constraint on sku by setting unique=False
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(max_length=60, unique=False),   # drop unique=True
        ),
        # ── Customer: add branch FK ──────────────────────────────────────────
        migrations.AddField(
            model_name="customer",
            name="branch",
            field=models.ForeignKey(
                null=True, blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customers",
                to="pos.branch",
            ),
        ),
        # ── Backfill existing rows ───────────────────────────────────────────
        migrations.RunPython(backfill_branch, reverse_code=migrations.RunPython.noop),
        # ── Make FKs non-nullable now that all rows have a branch ────────────
        migrations.AlterField(
            model_name="category",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="pos.branch",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="pos.branch",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customers",
                to="pos.branch",
            ),
        ),
        # ── Add per-branch unique constraints ────────────────────────────────
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=["branch", "name"], name="unique_category_per_branch"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=["branch", "sku"], name="unique_sku_per_branch"
            ),
        ),
    ]