# -*- coding: utf-8 -*-
# Generated by Django 5.2.1 on 2026-05-16 09:10
from django.db import migrations, models
import django.db.models.deletion


def set_default_branch(apps, schema_editor):
    """
    Set a default branch for all UserProfiles that don't have one.
    """
    UserProfile = apps.get_model('pos', 'UserProfile')
    Branch = apps.get_model('pos', 'Branch')
    # Get the first active branch, or create one if none exists?
    default_branch = Branch.objects.filter(is_active=True).order_by('id').first()
    if not default_branch:
        # Create a default branch if none exists? But we need a company too.
        Company = apps.get_model('pos', 'Company')
        company = Company.objects.filter(is_active=True).order_by('id').first()
        if not company:
            company = Company.objects.create(name='Demo Company', currency='KES', vat_rate=0)
        default_branch = Branch.objects.create(
            company=company,
            code='DEFAULT',
            name='Default Branch',
            is_active=True
        )
    # Set the branch for all UserProfiles with null branch to the default_branch
    UserProfile.objects.filter(branch__isnull=True).update(branch=default_branch)


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('pos', '0005_branch_scoping'),
    ]

    operations = [
        migrations.RunPython(set_default_branch, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='userprofile',
            name='branch',
            field=models.ForeignKey(
                blank=False,
                null=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='staff_profiles',
                to='pos.branch',
            ),
        ),
    ]
