# Generated by Django 5.2.1 on 2026-05-20 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0010_sales_returns_cash'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('security', models.JSONField(blank=True, default=dict)),
                ('system', models.JSONField(blank=True, default=dict)),
                ('pos_operations', models.JSONField(blank=True, default=dict)),
                ('stock_controls', models.JSONField(blank=True, default=dict)),
                ('notifications', models.JSONField(blank=True, default=dict)),
                ('financial', models.JSONField(blank=True, default=dict)),
                ('pricing', models.JSONField(blank=True, default=dict)),
                ('backup', models.JSONField(blank=True, default=dict)),
                ('integrations', models.JSONField(blank=True, default=dict)),
                ('super_admin', models.JSONField(blank=True, default=dict)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='pos.company')),
            ],
            options={
                'verbose_name_plural': 'Company settings',
            },
        ),
    ]
