# Generated by Django 5.2.1 on 2026-05-23 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0014_mpesastklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='mpesa_business_shortcode',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='branch',
            name='mpesa_callback_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='branch',
            name='mpesa_consumer_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='branch',
            name='mpesa_consumer_secret',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='branch',
            name='mpesa_environment',
            field=models.CharField(blank=True, choices=[('sandbox', 'Sandbox'), ('live', 'Live')], default='sandbox', max_length=16),
        ),
        migrations.AddField(
            model_name='branch',
            name='mpesa_passkey',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
