# Generated by Codex on 2026-05-28

from django.db import migrations, models
import django.db.models.deletion


def backfill_log_branches(apps, schema_editor):
    MpesaStkLog = apps.get_model("pos", "MpesaStkLog")
    for log in MpesaStkLog.objects.select_related("sale", "payment__sale"):
        branch_id = None
        if log.sale_id:
            branch_id = log.sale.branch_id
        elif log.payment_id and log.payment and log.payment.sale_id:
            branch_id = log.payment.sale.branch_id
        if branch_id:
            log.branch_id = branch_id
            log.save(update_fields=["branch"])


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0015_branch_mpesa_business_shortcode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mpesastklog",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mpesa_stk_logs",
                to="pos.branch",
            ),
        ),
        migrations.RunPython(backfill_log_branches, migrations.RunPython.noop),
    ]
