# Generated by Codex on 2026-05-29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0016_mpesastklog_branch"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="mpesa_direct_result_url",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="branch",
            name="mpesa_direct_timeout_url",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="branch",
            name="mpesa_initiator_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="branch",
            name="mpesa_security_credential",
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name="branch",
            name="mpesa_till_number",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name="MpesaDirectPaymentLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("transaction_id", models.CharField(db_index=True, max_length=120)),
                ("amount", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("payer_name", models.CharField(blank=True, max_length=160)),
                ("request", models.JSONField(blank=True, default=dict)),
                ("response", models.JSONField(blank=True, default=dict)),
                ("success", models.BooleanField(default=False)),
                ("message", models.CharField(blank=True, max_length=255)),
                ("originator_conversation_id", models.CharField(blank=True, db_index=True, max_length=120)),
                ("conversation_id", models.CharField(blank=True, db_index=True, max_length=120)),
                ("result_code", models.IntegerField(blank=True, null=True)),
                ("result_desc", models.CharField(blank=True, max_length=255)),
                ("branch", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="mpesa_direct_logs", to="pos.branch")),
                ("payment", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="mpesa_direct_logs", to="pos.payment")),
                ("sale", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="mpesa_direct_logs", to="pos.sale")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
