# Generated by Codex on 2026-05-29

from django.db import migrations, models


def backfill_mpesa_enable_flags(apps, schema_editor):
    Branch = apps.get_model("pos", "Branch")
    for branch in Branch.objects.all():
        branch.mpesa_stk_enabled = bool(
            branch.mpesa_consumer_key
            and branch.mpesa_consumer_secret
            and branch.mpesa_business_shortcode
            and branch.mpesa_passkey
            and branch.mpesa_callback_url
        )
        branch.mpesa_till_enabled = bool(
            branch.mpesa_consumer_key
            and branch.mpesa_consumer_secret
            and branch.mpesa_till_number
            and branch.mpesa_initiator_name
            and branch.mpesa_security_credential
            and branch.mpesa_direct_result_url
            and branch.mpesa_direct_timeout_url
        )
        branch.save(update_fields=["mpesa_stk_enabled", "mpesa_till_enabled"])


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0017_mpesa_direct_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="mpesa_stk_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="branch",
            name="mpesa_till_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(backfill_mpesa_enable_flags, migrations.RunPython.noop),
    ]
