# Generated by hand on 2026-05-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0018_branch_mpesa_enable_flags"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="mpesa_manual_approval_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
