# Generated by Django 5.2.14 on 2026-06-24 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0023_branch_code_per_company_pos_username'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='blacklistedtoken',
            name='pos_blackli_expires_idx',
        ),
        migrations.AlterField(
            model_name='blacklistedtoken',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['branch', 'is_active'], name='product_branch_active_idx'),
        ),
    ]
