# Generated by Django 5.2.14 on 2026-07-03 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0036_loyalty_credit_whatsapp_toggles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.CharField(blank=True, max_length=240)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('points', models.IntegerField()),
                ('transaction_type', models.CharField(choices=[('earn', 'Earned'), ('redeem', 'Redeemed'), ('adjustment', 'Adjustment')], max_length=20)),
                ('notes', models.CharField(blank=True, max_length=240)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='reportschedule',
            name='unique_report_schedule_per_branch_type',
        ),
        migrations.RenameIndex(
            model_name='discountrulelog',
            new_name='pos_discoun_branch__3a1e05_idx',
            old_name='pos_discoun_branch__idx',
        ),
        migrations.RenameIndex(
            model_name='priceschedulelog',
            new_name='pos_pricesc_branch__90eea9_idx',
            old_name='pos_pricesch_branch__idx',
        ),
        migrations.AddField(
            model_name='companysettings',
            name='credit_loyalty',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AlterUniqueTogether(
            name='reportschedule',
            unique_together={('branch', 'report_type')},
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('phone__gt', '')), fields=('branch', 'phone'), name='unique_customer_phone_per_branch'),
        ),
        migrations.AddField(
            model_name='creditrepayment',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_repayments', to='pos.branch'),
        ),
        migrations.AddField(
            model_name='creditrepayment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_repayments', to='pos.customer'),
        ),
        migrations.AddField(
            model_name='creditrepayment',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loyaltytransaction',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_transactions', to='pos.branch'),
        ),
        migrations.AddField(
            model_name='loyaltytransaction',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_transactions', to='pos.customer'),
        ),
        migrations.AddField(
            model_name='loyaltytransaction',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loyaltytransaction',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.sale'),
        ),
    ]
