# Generated by Django 5.2.14 on 2026-07-03 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0037_creditrepayment_loyaltytransaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditrepayment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='creditrepayment',
            name='reference',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='creditrepayment',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_repayments', to='pos.shift'),
        ),
    ]
